### ISSUE TITLE
江湖救急

### ISSUE THREAD

**Issue by liangklfangl** [IndexXuan/v2ex-api-bridge#1]
您好，看到你fork了我的[仓库](https://github.com/liangklfangl/),里面有部分内容写的有问题，能麻烦删除下吗？如果有疑问可以加我的微信:微信号为liangklfang 昵称(幻海之巅)，谢谢啦。也希望后续有机会共同探讨。

**Comment by IndexXuan** [comment]
@liangklfangl 哪个啊 ？请具体指出

**Comment by liangklfangl** [comment]
> @liangklfangl 哪个啊 ？请具体指出

就是这个哦，https://github.com/IndexXuan/react-article-bucket
